services:
  prestashop:  # Define un servicio llamado "prestashop".
    image: prestashop/prestashop  # Utiliza la imagen oficial de PrestaShop.
    ports:
      - 8080:80  # Asocia el puerto 8080 de tu máquina con el puerto 80 del contenedor PrestaShop.
    environment:
      - DB_SERVER=prestashop-db  # Configura la dirección de la base de datos.
      - DB_NAME=prestashop  # Define el nombre de la base de datos.
      - DB_USER=prestashop  # Especifica el usuario de la base de datos.
      - DB_PASSWD=prestashop  # Establece la contraseña de la base de datos.
    volumes:
      - ./prestashop:/var/www/html  # Monta una carpeta local en el contenedor PrestaShop para gestionar archivos.
    depends_on:
      - prestashop-db  # Asegura que el servicio "prestashop-db" se inicie antes del servicio "prestashop".

  prestashop-db:  # Define un servicio para la base de datos.
    image: mysql:5.7  # Utiliza la imagen oficial de MySQL versión 5.7.
    environment:
      - MYSQL_ROOT_PASSWORD=someprestashop  # Establece la contraseña de administrador de la base de datos.
      - MYSQL_DATABASE=prestashop  # Crea una base de datos llamada "prestashop".
      - MYSQL_USER=prestashop  # Define un usuario de la base de datos.
      - MYSQL_PASSWORD=prestashop  # Establece la contraseña del usuario de la base de datos.
    volumes:
      - ./mysql:/var/lib/mysql  # Monta una carpeta local en el contenedor de MySQL para persistencia de datos.